version: '3.7'

services:
  app:
    #image : "stefanosedano/views_competition_docker:latest"
    build:
      context: .
    ports:
      - "80:80"
    #volumes:
    #  - ../CODE:/CODE
    command:
      - sh
      - -c
      - tail -f /dev/null
